### ISSUE TITLE
execution containers #13 failed

### ISSUE THREAD

**Issue by brucellino** [AAROC/CODE-RADE-client#1]
Build 'execution containers' is failing!

Last 50 lines of build output:

```
[...truncated 5.11 KB...]
Run condition [Current build status] enabling perform for step [Execute shell]
[exec_containers] $ /bin/sh -xe /tmp/jenkins4198471219475154127.sh
+ source coderade/bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/sh ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/var/lib/jenkins/exec_containers/coderade
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ PATH=/var/lib/jenkins/exec_containers/coderade/bin:/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /var/lib/jenkins/exec_containers/coderade
++ PS1='(coderade) '
++ export PS1
++ alias pydoc
++ '[' -n /bin/sh ']'
++ hash -r
+ ansible-container push --push-to=quay
Parsing conductor CLI args.
Engine integration loaded. Preparing push.	engine=Docker™ daemon
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 959, in conductorcmd_push
    username, password = engine.login(username, password, email, url, config_path)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 1120, in login
    u'Please provide login credentials for registry {}.'.format(url))
container.exceptions.AnsibleContainerConductorException: Please provide login credentials for registry https://quay.io/.
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=de07ea8f825ccb4127f7b506ec73af3b4573a4b87ebe3e309c72d10991db4273 save_container=False
ERROR	Conductor exited with status 1	
Build step 'Conditional step (single)' marked build as failure

```

Changes since last successful build:
No changes
No changes
No changes
No changes
No changes
No changes
No changes
No changes
No changes
No changes
No changes
No changes
No changes

[View full output](https://ci.sagrid.ac.za/job/execution%20containers/13/)

**Comment by brucellino** [comment]
Build was fixed!
